Fixed Several errors
Notice: Use of undefined constant DS - assumed 'DS' in /joomla/modules/mod_ninja_rss_syndicator/mod_ninja_rss_syndicator.php on line 15
Fatal error: require_once(): Failed opening required '/joomla/modules/mod_ninja_rss_syndicatorDShelper.php' 
(include_path='.:/usr/lib/php5.4') in /joomla/modules/mod_ninja_rss_syndicator/mod_ninja_rss_syndicator.php on line 15
Strict Standards: Non-static method modNinjaRssSyndicatorHelper::getNinjaRssSyndicatorFeeds() should not be called statically in 
/joomla/modules/mod_ninja_rss_syndicator/mod_ninja_rss_syndicator.php on line 22